<a href="https://colab.research.google.com/github/jdasam/aat3020-2023/blob/main/notebooks/4_Machine_translation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machine Translation

In [ ]:
# install HuggingFace
!pip install transformers tokenizers

# If you are not using Colab, install below to read xlsx file
# !pip install openpyxl

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 97.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 104.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 28.8 MB/s eta 0:00:00


In [1]:
'''
Download dataset (originally from NIA AI-Hub)
'''

# !gdown 1CpsqOuuuB3I_PG5DbuqH1ssCFVerU46g
# !unzip -q nia-aihub-korean-english.zip

!gdown 1GMFWREWBVcD5vJdwNFadHmzVStclcyKf
!unzip -q nia-aihub-korean-english-txt.zip

Downloading...
From (uriginal): https://drive.google.com/uc?id=1GMFWREWBVcD5vJdwNFadHmzVStclcyKf
From (redirected): https://drive.google.com/uc?id=1GMFWREWBVcD5vJdwNFadHmzVStclcyKf&confirm=t&uuid=65827053-9650-47c0-bcea-16500524b0f4
To: /home/teo/userdata/git_libraries/aat3020-2023/notebooks/nia-aihub-korean-english-txt.zip
100%|████████████████████████████████████████| 449M/449M [00:55<00:00, 8.14MB/s]


In [2]:
from pathlib import Path
import pandas as pd


In [3]:
# You don't have to run this
'''
dataset_dir = Path('nia_korean_english')
data_list = sorted(list(dataset_dir.glob('*.xlsx')))
for path in data_list:
  df = pd.read_excel(path)
  kor_text_path = path.parent / (path.stem+'_kor.txt') 
  eng_text_path = path.parent / (path.stem+'_eng.txt') 
  with open(kor_text_path, 'w', encoding='utf8') as f:
      f.write('\n'.join(df['원문']))
  with open(eng_text_path, 'w', encoding='utf8') as f:
      f.write('\n'.join(df['번역문']))
'''


"\ndataset_dir = Path('nia_korean_english')\ndata_list = sorted(list(dataset_dir.glob('*.xlsx')))\nfor path in data_list:\n  df = pd.read_excel(path)\n  kor_text_path = path.parent / (path.stem+'_kor.txt') \n  eng_text_path = path.parent / (path.stem+'_eng.txt') \n  with open(kor_text_path, 'w', encoding='utf8') as f:\n      f.write('\n'.join(df['원문']))\n  with open(eng_text_path, 'w', encoding='utf8') as f:\n      f.write('\n'.join(df['번역문']))\n"

In [4]:
dataset_dir = Path('nia_korean_english')
data_list = sorted(list(dataset_dir.glob('*.xlsx')))

data_list

[PosixPath('nia_korean_english/1_구어체(1).xlsx'),
 PosixPath('nia_korean_english/1_구어체(2).xlsx'),
 PosixPath('nia_korean_english/2_대화체.xlsx'),
 PosixPath('nia_korean_english/3_문어체_뉴스(1)_200226.xlsx'),
 PosixPath('nia_korean_english/3_문어체_뉴스(2).xlsx'),
 PosixPath('nia_korean_english/3_문어체_뉴스(3).xlsx'),
 PosixPath('nia_korean_english/3_문어체_뉴스(4).xlsx'),
 PosixPath('nia_korean_english/4_문어체_한국문화.xlsx'),
 PosixPath('nia_korean_english/5_문어체_조례.xlsx'),
 PosixPath('nia_korean_english/6_문어체_지자체웹사이트.xlsx')]

In [14]:
import pandas as pd

dfs = [pd.read_excel(path) for path in data_list]

/home/teo/.local/share/virtualenvs/aat3020-2023-E1AG9i7b/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/home/teo/.local/share/virtualenvs/aat3020-2023-E1AG9i7b/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/home/teo/.local/share/virtualenvs/aat3020-2023-E1AG9i7b/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/home/teo/.local/share/virtualenvs/aat3020-2023-E1AG9i7b/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Wor

In [15]:
df = pd.concat(dfs, axis=0)

In [ ]:
with open("nia_korean_english/1_구어체(1)_kor.txt", 'w', encoding='utf8') as f:
    f.write('\n'.join(df['원문']))


In [ ]:
df['원문'][10000:10050], df['번역문'][10000:10050]

## Huggingface Tokenizer

In [8]:
from tokenizers import BertWordPieceTokenizer
tokenizer = BertWordPieceTokenizer(strip_accents=False, lowercase=False)

num_files = len(data_list)

corpus_file   =  [str(path.parent / (path.stem + '_kor.txt')) for path in data_list[:num_files]]
# output_dir   = Path('hugging_kor_%d'%(vocab_size))
en_corpus_file   =  [str(path.parent / (path.stem + '_eng.txt')) for path in data_list[:num_files]]
# output_dir   = Path('hugging_eng_%d'%(vocab_size))

vocab_size    = 32000  # Number of maximum size of the vocabulary
limit_alphabet= 6000   
output_dir    = Path('hugging_kor_%d'%(vocab_size))
en_output_dir = Path('hugging_eng_%d'%(vocab_size))
output_dir.mkdir(exist_ok=True)
en_output_dir.mkdir(exist_ok=True)
min_frequency = 5 

tokenizer.train(files=corpus_file,
               vocab_size=vocab_size,
               min_frequency=min_frequency,
               limit_alphabet=limit_alphabet, 
               show_progress=True)

tokenizer.save_model(str(output_dir))

en_tokenizer = BertWordPieceTokenizer(strip_accents=False, lowercase=False)
en_tokenizer.train(files=en_corpus_file,
                vocab_size=vocab_size,
                min_frequency=min_frequency,
                limit_alphabet=limit_alphabet,
                show_progress=True)
en_tokenizer.save_model(str(en_output_dir))



['hugging_eng_32000/vocab.txt']

In [11]:
!zip -r nia-aihub-korean-english-vocab.zip nia_korean_english hugging_kor_32000 hugging_eng_32000

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
  adding: nia_korean_english/ (stored 0%)
  adding: nia_korean_english/5_문어체_조례.xlsx (deflated 3%)
  adding: nia_korean_english/3_문어체_뉴스(2).xlsx (deflated 0%)
  adding: nia_korean_english/2_대화체.xlsx (deflated 9%)
  adding: nia_korean_english/1_구어체(1).xlsx (deflated 3%)
  adding: nia_korean_english/1_구어체(1)_eng.txt (deflated 64%)
  adding: nia_korean_english/3_문어체_뉴스(4).xlsx (deflated 0%)
  adding: nia_korean_english/2_대화체_kor.txt (deflated 69%)
  adding: nia_korean_english/4_문어체_한국문화_kor.txt (deflated 63%)
  adding: nia_korean_english/5_문어체_조례_kor.txt (deflated 72%)
  adding: nia_korean_english/6_문어체_지자체웹사이트_kor.txt (deflated 65%)
  adding: nia_korean_english/1_구어체(2)

In [12]:
from transformers import BertTokenizerFast

tokenizer_src = BertTokenizerFast.from_pretrained('hugging_kor_32000',
                                                       strip_accents=False,
                                                       lowercase=False) 
tokenizer_tgt = BertTokenizerFast.from_pretrained('hugging_eng_32000',
                                                       strip_accents=False,
                                                       lowercase=False) 

tokenized_data = tokenizer_src(df['원문'].iloc[10])
print(df['원문'].iloc[10])
print(tokenizer_src.decode(tokenized_data['input_ids']))

나는 친구에게 그 철학자의 책을 선물해 주겠다고 말했습니다.
[CLS] 나는 친구에게 그 철학자의 책을 선물해 주겠다고 말했습니다. [SEP]


In [ ]:
tokenized_data['input_ids']

In [31]:
tokenized_ids = tokenizer_src("나는 서강대학교에 다닙니다")['input_ids']
tokenized_ids

[2, 3715, 1079, 2604, 12638, 12008, 3]

In [32]:
tokenizer_src.decode(tokenized_ids)

'[CLS] 나는 서강대학교에 다닙니다 [SEP]'

## Divide Train / Validate/ Test Set
- using `np.random.choice`
    - To always get the same random shuffling result, you have to use `np.random.seed()`

In [33]:
df

ID     지자체                                                 원문  \
0       261811     경기도  "경기도가 말산업 육성을 위해 총예산 245,193천원으로 2013년 경기도 용인시...   
1       409852     경기도  "경기도가 주최하고 경기FTA활용지원센터와 코트라가 주관한 이번 시장개척단은 지난 ...   
2       352671     경기도  "경기도가 주최하고 경기도비정규직지원센터가 주관한 이번 교육은 공공 부문이 직·간접...   
3       308191     경기도  "경기도가 주최하고 사단법인 한국장애인복지시설협회 경기도협회(대표자:정권)에서 주관...   
4       185424     경기도  "경기도가 주최하고 인구보건복지협회 경기지회, 아이낳기좋은세상 경기운동본부가 주관하...   
...        ...     ...                                                ...   
100082   73961  서울시 중구  힐튼호텔 건너편에서 회현동주민센터로 내려가는 길에는 칙칙한 회색의 석축옹벽이 이어져...   
100083  462950     경기도  힘든 분들이 많이 계시지만 조금이나마 어렵지 않도록 도움이 될 수 있도록 저희가 최...   
100084  333006     경기도  힘든 역사 속에서 대한민국을 불과 50여년 만에 빛나는 나라로 만들고 업적을 만들 ...   
100085  454399     경기도  힘든 일을 하는 데는 무엇보다 정부가 큰 관심을 갖고 있다는 자부심을 갖도록 해야 한다.   
100086  507679     경기도  힘을 합쳐 세계 일류통일강국으로 대한민국을 우뚝 세우는 역할을 이 자리의 모든 지도...   

                                                      번역문  
0       "The Gyeonggi provincial government announced ...  
1       "Organized by Gyeonggi provincial government a...  
2       "Organized by Gyeonggi provincial government a...  
3       "Organized by Gyeonggi provincial government a...  
4       "Hosted by Gyeonggi provincial government, org...  
...                                                   ...  
100082  Across from the Hilton Hotel, the path to Hoeh...  
100083  There are a lot of people who are having a har...  
100084  It was possible to make the Republic of Korea ...  
100085  As for doing hard work, most of all, they shou...  
100086  I would like to thank all the leaders here for...  

[100087 rows x 4 columns]

In [18]:
len(df)

1602418

In [38]:
df.iloc[-1]

ID                                                507679
지자체                                                  경기도
원문     힘을 합쳐 세계 일류통일강국으로 대한민국을 우뚝 세우는 역할을 이 자리의 모든 지도...
번역문    I would like to thank all the leaders here for...
Name: 100086, dtype: object

In [39]:
df = pd.read_excel("/content/nia_korean_english/1_구어체(1).xlsx")

## Define Dataset
- Each datasample has to return source sentence and target sentence
- You need a Tokenizer to get the tokenized result


In [19]:
import torch

class Dataset:
  def __init__(self, df, src_tokenizer, tgt_tokenizer):
    self.data = df
    self.src_tokenizer = src_tokenizer
    self.tgt_tokenizer = tgt_tokenizer
  
  def __len__(self):
    return len(self.data)

  def __getitem__(self, idx):
    selected_row = self.data.iloc[idx]
    source = selected_row['원문']
    target = selected_row['번역문']

    source_enc = self.src_tokenizer(source)['input_ids']
    target_enc = self.tgt_tokenizer(target)['input_ids']

    return torch.LongTensor(source_enc), torch.LongTensor(target_enc[:-1]), torch.LongTensor(target_enc[1:])
  
dataset = Dataset(df, tokenizer_src, tokenizer_tgt)

source, target, shifted_target = dataset[0]
print(source)
print(target)
print(shifted_target)

tensor([    2,    11,    70,  4665,  5209, 13306,    71, 12901,  9565, 12435,
           11,  3546, 14567,  4325,  8934,  8407,  7400,  4154,  3252,  6420,
        12985,  4996,  3397,  6461,    18,     3])
tensor([    2, 26268, 23067,    11,  1056,    69, 23067,  2803,  1067,  5155,
         1117,  1042,  2405,  4024,  5520,  1039,  1023, 26268,    18])
tensor([26268, 23067,    11,  1056,    69, 23067,  2803,  1067,  5155,  1117,
         1042,  2405,  4024,  5520,  1039,  1023, 26268,    18,     3])


## Split Dataset
- using ``torch.utils.data.random_split(dataset)``

In [20]:
num_data = len(dataset)
# num_data
num_train = int(num_data * 0.8)
num_valid = int(num_data * 0.1)
# num_test = int(num_data * 0.1)
num_test = num_data - (num_train + num_valid)

train_set, valid_set, test_set = torch.utils.data.random_split(dataset, [num_train, num_valid, num_test])
print(len(train_set), len(valid_set), len(test_set))

1281934 160241 160243


In [21]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader

In [22]:
train_loader = DataLoader(train_set, batch_size=1, shuffle=True)

batch = next(iter(train_loader))
batch

[tensor([[    2,  3318,  4506,  5072,  4326,  7277, 10197, 14775,  7277,  8680,
           8472,  7973, 25836, 14094, 13079,  4331,  6426,   104, 13246,  7227,
          13768,  6705,  9246, 12502,  6482, 12822,  3318,  4506,  5072,  8878,
           6476, 14332, 12319,    18,     3]]),
 tensor([[   2, 1023, 2673, 6269, 1067, 1023, 4139, 1106,   69, 1495,   17, 1949,
          4139, 1644,   69, 5867, 1039, 1334, 8757, 1045, 1787, 1970, 1319, 1039,
          1334, 6679, 1045, 7405,   16, 1169, 1106, 8088, 1392, 2151, 1089, 1106,
            69, 1495,   17, 1949, 4139, 1142, 2709,   17, 4430,   18]]),
 tensor([[1023, 2673, 6269, 1067, 1023, 4139, 1106,   69, 1495,   17, 1949, 4139,
          1644,   69, 5867, 1039, 1334, 8757, 1045, 1787, 1970, 1319, 1039, 1334,
          6679, 1045, 7405,   16, 1169, 1106, 8088, 1392, 2151, 1089, 1106,   69,
          1495,   17, 1949, 4139, 1142, 2709,   17, 4430,   18,    3]])]

## Define Collate function
- After implementing Dataset, we have to declare DataLoader that groups several training samples as a single batch
- However, we cannot batchify the melodies in straightforward way, because the length of each melody is different
- In this problem, you will learn about how to handle sequences of different length as a batch


In [ ]:

'''
This cell will make error, because the length of each sample is different to each other
'''

train_loader = DataLoader(train_set, batch_size=8)
batch = next(iter(train_loader))


In [ ]:
'''
To handle that problem, you have to make your collate function 
'''
def your_collate_function(raw_batch):
  '''
  You can make your own function to handle the batch
  '''
  
  return raw_batch[0] # This returns the first melody of each batch. So it will avoid the error, but it doesn't do proper batchifying

batch_size = 8
raw_batch = [train_set[i] for i in range(batch_size)] # This is the input for the collate function
batch = your_collate_function(raw_batch)

'''
This is what the 'collate_fn' does in DataLoader
'''

train_loader = DataLoader(train_set, batch_size=batch_size, collate_fn=your_collate_function)
batch_by_loader = next(iter(train_loader))

#### Pad Sequence and Pack Sequence
In PyTorch, there are two ways to batchify a group of sequence with different length.
- `torch.nn.utils.rnn.pad_sequence`
    - This function takes list of tensors with different length and return padded sequence
    - Padding is adding some constant number as a PAD token to match the length of short sequence to the maximum length
        - e.g. If there are sequence of length (3,7,4), we can add 4 zeros to sequence with length 3, 3 zeros to sequence with length 4 to make them length 7
    - In default, we use 0 for padding (zero padding)
    - The result 
- `torch.nn.utils.rnn.pack_sequence`
    - pad_sequence 

Cells below show the example of `pad_sequence`

In [23]:
from torch.nn.utils.rnn import pad_sequence, pack_sequence, PackedSequence
short = torch.arange(3, -1, -1).float() # [3, 2, 1, 0]
long = torch.arange(27,19, -1).float()
middle = torch.arange(15,9, -1).float()

pad_sequence([short, long, middle], batch_first=False)  # T x N 

tensor([[ 3., 27., 15.],
        [ 2., 26., 14.],
        [ 1., 25., 13.],
        [ 0., 24., 12.],
        [ 0., 23., 11.],
        [ 0., 22., 10.],
        [ 0., 21.,  0.],
        [ 0., 20.,  0.]])

In [ ]:
# Default value of batch_first in pad_sequence is False.
# So you have to always be careful not to miss batch_first=True in pad_sequence, if you use batch_first=True for your RNN layer.
pad_sequence([short, long, middle], batch_first=True)  # N x T 

1) However, the problem is that you can't figure out whether the 0 at the end of each sequence is a padded one, or was included in the original sequence
- e.g. `[2, 3, 4, 3, 0]` becomes `[ 2,  3,  4,  5,  0,  0,  0]`. Now we don't know how many zeros were added for padding

2) Also, if you run RNN for this padded sequence, RNN will calculate for the padded part also.
- RNN doesn't know whether it is padded data, or existing data
- This makes computation slower

3) If you want to use bi-directional, which also reads the sequence from backward, paddings can make the result different.

To solve this issue, we use PackedSequence, by using `pack_sequence`/

In [ ]:
packed_sequence = pack_sequence([short, long, middle], enforce_sorted=False)
packed_sequence

`PackedSequence` has `data` and `batch_sizes`
- `data` contains the flattened value of given batch
    - To optimize the computation, the sequences have to be sorted by descending of length
- `batch_sizes` represents how many valid batch sample exists for each time step
    - `[3, 3, 3, 2, 2, 1, 1]` means that there are 3 sequences for first three time steps, and then 2 sequences for next two steps, and then only 1 sequence for next two steps.
- `sorted_indices` shows how the sorted sequences can be converted to original order.
    - `[1,2,0]` means that 
        - the 0th sequence in the sorted sequences (the longest one) was indexed as 1 in the original input batch
        - the 1st sequence in the sorted sequences (`middle`) was indexed as 2 in the original input batch
        - the 2nd sequence in the sorted sequences (`short`) was index as 0 in the original input batch
- `unsorted_indices` shows how the original sequences are sorted.
    - `[2,0,1]` means that
        - the 0th sequence in the original input was sorted as 2nd in the sorted sequences

In [ ]:
rnn_layer = nn.GRU(1, 1)
packed_sequence = pack_sequence([short.unsqueeze(1), long.unsqueeze(1), middle.unsqueeze(1)], enforce_sorted=False)
out, last_hidden = rnn_layer(packed_sequence)

print(f"Type of output of RNN for PackedSequence: {type(out)}")
print(f"Type of last_hidden of RNN for PackedSequence: {type(last_hidden)}")

- RNN or its family of PyTorch can automatically handle `PackedSequence`
- However, other layers like `nn.Embedding` or `nn.Linear` cannot take `PackedSequence` as its input
- There are two ways to feed `PackedSequence` to these layers
    - First, convert PackedSequence to ordinary torch.Tensor by `torch.nn.utils.rnn.pad_packed_sequence`
        - This will convert PackedSequence to a tensor of sequneces with same length but different padding
    - The other way is to feed only PackedSequence.data, and then declaring new PackedSequence with the output as `data`

In [ ]:
'''
This will make error, because other layers cannot handle PackedSequence
'''
test_linear_layer = nn.Linear(in_features=1, out_features=2)
test_linear_layer(packed_sequence)

In [ ]:
'''
One way to to this is using torch.nn.utils.rnn.pad_packed_sequence to convert PackedSequence to ordinary tensor
'''

from torch.nn.utils.rnn import pad_packed_sequence
padded_sequence, batch_lengths = pad_packed_sequence(packed_sequence)
print(f'The padded sequence generated from packed sequence (squeezed for printing): \n {padded_sequence.squeeze()}')
print(f'"pad_packed_sequence" also returns "batch_lengths", to clarify the original length before the padding: \n {batch_lengths}')



In [ ]:
'''
Now you can feed padded sequence to linear layer.
'''

linear_output = test_linear_layer(padded_sequence)
print(f"Output of feeding padded_sequence to a linear layer: {linear_output}")
print("Caution that it returns non-zero values for timestep with zero padding, because linear layer has a bias")

In [ ]:
'''
You can make the output as a PackedSequence, by using torch.nn.utils.rnn.pack_padded_sequence
'''
from torch.nn.utils.rnn import pack_padded_sequence
re_packed_sequence = pack_padded_sequence(linear_output, batch_lengths, enforce_sorted=False)
re_packed_sequence

In [ ]:
'''
Another way to do it is using PackedSequence.data
'''

linear_out_pack = test_linear_layer(packed_sequence.data)
packed_sequence_after_linear = PackedSequence(linear_out_pack, packed_sequence.batch_sizes, packed_sequence.sorted_indices, packed_sequence.unsorted_indices)
packed_sequence_after_linear

In [27]:
def pack_collate(raw_batch):
  source, target, shifted_target = zip(*raw_batch)
  return pack_sequence(source, enforce_sorted=False), pack_sequence(target, enforce_sorted=False), pack_sequence(shifted_target, enforce_sorted=False)

train_loader = DataLoader(train_set, batch_size=8, collate_fn=pack_collate)
batch = next(iter(train_loader))
batch

(PackedSequence(data=tensor([    2,     2,     2,     2,     2,     2,     2,     2,  7211,  3536,
          8201,  7203,  6587,  6651,  6528,  7458,   145,  7007, 13314,  6977,
          4177, 13846,  3228, 11457,  3453, 10221,  4313, 30734, 14375,  7516,
         29408,  4330,  5618, 12647, 25349,  9928, 10639,  7327, 16802,  6435,
          4396, 23625,  6468,  4531,  6422,  6803, 21664,  6639,   146,  6723,
            82, 11507, 22937,  2185,  2396,  7135,    16,  7375,  4856,  4330,
         28107,  3578, 10831, 17205,   145, 28360,  4496,  6435,  8861, 17765,
          3252,  4436, 28943,  7486,  4464, 16118, 10727, 10261,  4432,  3252,
         28943, 31367,  4330,  4325, 13043,  6678,  4387,  6507, 28943, 10874,
          7249, 11031,    16,  3304, 24513,    18,   146, 17005,  4562, 10566,
         22046, 13655,    18,     3,    16, 12945, 28906,    16, 17689,    18,
             3,   145, 18515, 12678,  9468, 14760,     3,  8703,    16,  4387,
          4322,  6435, 24557, 18

## Define Model
![image](https://raw.githubusercontent.com/tensorflow/nmt/master/nmt/g3doc/img/seq2seq.jpg)

In [30]:
class Seq2seq(nn.Module):
  def __init__(self, enc_vocab, dec_vocab, hidden_size):
    super().__init__()
    self.encoder = Encoder(enc_vocab, hidden_size)
    self.decoder = Decoder(dec_vocab, hidden_size)

  def forward(self, src, tgt):
    enc_out = self.encoder(src)
    dec_out = self.decoder(tgt, enc_out)
    return dec_out 

class Encoder(nn.Module):
  def __init__(self, num_vocab, hidden_size, num_layers=2):
    super().__init__()
    self.emb = nn.Embedding(num_vocab, hidden_size)
    self.rnn = nn.GRU(hidden_size, hidden_size, batch_first=True, num_layers=num_layers)
    # batch_first True: it takes (Num_samples_in_batch, num_timesteps, num_dim)
    # batch_first False: it takes (num_timesteps, Num_samples_in_batch, num_dim)

  def forward(self, x):
    if isinstance(x, PackedSequence):
      emb = PackedSequence(self.emb(x.data), batch_sizes=x.batch_sizes, sorted_indices=x.sorted_indices, unsorted_indices=x.unsorted_indices)
    else:
      emb = self.emb(x)
    out, last_hidden = self.rnn(emb)
    return last_hidden


class Decoder(nn.Module):
  def __init__(self, num_vocab, hidden_size, num_layers=2):
    super().__init__()
    self.emb = nn.Embedding(num_vocab, hidden_size)
    self.rnn = nn.GRU(hidden_size, hidden_size, batch_first=True, num_layers=num_layers)
    self.proj = nn.Linear(hidden_size, num_vocab)


  def forward(self, x, enc_output):
    if isinstance(x, PackedSequence):
      emb = PackedSequence(self.emb(x.data), batch_sizes=x.batch_sizes, sorted_indices=x.sorted_indices, unsorted_indices=x.unsorted_indices)
      out, last_hidden = self.rnn(emb, enc_output)
      logit = PackedSequence(self.proj(out.data), batch_sizes=out.batch_sizes, sorted_indices=out.sorted_indices, unsorted_indices=out.unsorted_indices)
    else:
      emb = self.emb(x)
      out, last_hidden = self.rnn(emb, enc_output)
      logit = self.proj(out)
    return logit

hidden_size = 64
model = Seq2seq(tokenizer_src.vocab_size, tokenizer_tgt.vocab_size, hidden_size)
encoder = Encoder(tokenizer_src.vocab_size, hidden_size)
decoder = Decoder(tokenizer_tgt.vocab_size, hidden_size)

src, tgt, shifted_tgt = batch

enc_out = encoder(src)
dec_out = decoder(tgt, enc_out)

logit = model(src, tgt)
# logit.shape, logit.softmax(dim=-1)

In [80]:
logit.shape, shifted_tgt.shape, shifted_tgt

(torch.Size([1, 10, 30679]),
 torch.Size([1, 10]),
 tensor([[  76,   10,  746,  810,  906,  335,  412, 2590,   17,    3]]))

In [33]:
def nll_loss(pred, target, eps=1e-8):
  if pred.ndim == 3:
    pred = pred.flatten(0, 1)
  if target.ndim == 2:
    target = target.flatten(0, 1)
  assert pred.ndim == 2
  assert target.ndim == 1

  
  return -torch.log(pred[torch.arange(len(target)), target] + eps).mean()

# loss = nll_loss(logit.softmax(dim=-1), shifted_tgt)
# loss, loss.shape, shifted_tgt

## Define Trainer

In [34]:
from tqdm.auto import tqdm

class Trainer:
  def __init__(self, model, optimizer, loss_fn, train_loader, valid_loader, device):
    self.model = model
    self.optimizer = optimizer
    self.loss_fn = loss_fn
    self.train_loader = train_loader
    self.valid_loader = valid_loader
    
    self.model.to(device)
    
    self.best_valid_accuracy = 0
    self.device = device
    
    self.training_loss = []
    self.validation_loss = []
    self.validation_acc = []

  def save_model(self, path='kor_eng_translator_model.pt'):
    torch.save({'model':self.model.state_dict(), 'optim':self.optimizer.state_dict()}, path)
    
  def train_by_num_epoch(self, num_epochs):
    for epoch in tqdm(range(num_epochs)):
      self.model.train()
      for batch in tqdm(self.train_loader, leave=False):
        loss_value = self._train_by_single_batch(batch)
        self.training_loss.append(loss_value)
      self.model.eval()
      validation_loss, validation_acc = self.validate()
      self.validation_loss.append(validation_loss)
      self.validation_acc.append(validation_acc)
      
      if validation_acc > self.best_valid_accuracy:
        print(f"Saving the model with best validation accuracy: Epoch {epoch+1}, Acc: {validation_acc:.4f} ")
        self.save_model('kor_eng_translator_model_best.pt')
      else:
        self.save_model('kor_eng_translator_model_last.pt')
      self.best_valid_accuracy = max(validation_acc, self.best_valid_accuracy)

      
  def _train_by_single_batch(self, batch):
    '''
    This method updates self.model's parameter with a given batch
    
    batch (tuple): (batch_of_input_text, batch_of_label)
    
    You have to use variables below:
    
    self.model (SentimentModel/torch.nn.Module): A neural network model
    self.optimizer (torch.optim.adam.Adam): Adam optimizer that optimizes model's parameter
    self.loss_fn (function): function for calculating BCE loss for a given prediction and target
    self.device (str): 'cuda' or 'cpu'

    output: loss (float): Mean binary cross entropy value for every sample in the training batch
    The model's parameters, optimizer's steps has to be updated inside this method

    TODO: Complete this method 
    '''
    src, tgt, shifted_tgt = batch
    src = src.to(self.device)
    tgt = tgt.to(self.device)
    shifted_tgt = shifted_tgt.to(self.device)

    logit = self.model(src, tgt)

    if isinstance(logit, PackedSequence):
      prob = logit.data.softmax(dim=-1)
      loss = self.loss_fn(prob, shifted_tgt.data)
    else:
      loss = self.loss_fn(prob, shifted_tgt)
    loss.backward()
    self.optimizer.step()
    self.optimizer.zero_grad

    return loss.item()

    
  def validate(self, external_loader=None):
    '''
    This method calculates accuracy and loss for given data loader.
    It can be used for validation step, or to get test set result
    
    input:
      data_loader: If there is no data_loader given, use self.valid_loader as default.
      
    
    output: 
      validation_loss (float): Mean Binary Cross Entropy value for every sample in validation set
      validation_accuracy (float): Mean Accuracy value for every sample in validation set
      
    TODO: Complete this method 

    '''
    
    ### Don't change this part
    if external_loader and isinstance(external_loader, DataLoader):
      loader = external_loader
      print('An arbitrary loader is used instead of Validation loader')
    else:
      loader = self.valid_loader
      
    self.model.eval()
    
    '''
    Write your code from here, using loader, self.model, self.loss_fn.
    '''

hidden_size = 128
model = Seq2seq(tokenizer_src.vocab_size, tokenizer_tgt.vocab_size, hidden_size)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
loss_fn = nll_loss
train_loader = DataLoader(train_set, batch_size=64, shuffle=True, collate_fn=pack_collate)
valid_loader = DataLoader(valid_set, batch_size=128, shuffle=False, collate_fn=pack_collate)
device = 'cuda'

trainer = Trainer(model, optimizer, loss_fn, train_loader, valid_loader, device)


In [35]:
loss_records = []

for i in range(100):
  loss = trainer._train_by_single_batch(batch)
  loss_records.append(loss)
print(loss_records)

[10.386933326721191, 10.32657241821289, 10.268647193908691, 10.210345268249512, 10.149768829345703, 10.084954261779785, 10.013751029968262, 9.933724403381348, 9.842076301574707, 9.735479354858398, 9.609955787658691, 9.460831642150879, 9.283170700073242, 9.072586059570312, 8.827017784118652, 8.548736572265625, 8.245342254638672, 7.928269863128662, 7.609827041625977, 7.30034065246582, 7.006803512573242, 6.732766628265381, 6.479230880737305, 6.245960235595703, 6.0324931144714355, 5.8385162353515625, 5.663750171661377, 5.507776737213135, 5.369976997375488, 5.249426364898682, 5.144853115081787, 5.054716110229492, 4.977362632751465, 4.911262035369873, 4.85506534576416, 4.807579517364502, 4.767537593841553, 4.733421802520752, 4.70345401763916, 4.676103115081787, 4.650460720062256, 4.626137733459473, 4.6028008460998535, 4.580265998840332, 4.558821201324463, 4.539508819580078, 4.523560523986816, 4.511585235595703, 4.503292083740234, 4.497927665710449, 4.4949469566345215, 4.494128704071045, 4.49

In [ ]:
trainer.train_by_num_epoch(1)

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/160000 [00:00<?, ?it/s]

In [ ]:
!gdown 10PR89HB2h2dKiXw-4GWQyhGvAOds3WKZ


In [ ]:
model = Seq2seq(tokenizer_src.vocab_size, tokenizer_tgt.vocab_size, hidden_size, num_layers=3)
